# Build & deploy TouristGuide (JAR) to Azure Web App - touristguidephab

name: Build and deploy JAR app to Azure Web App - touristguidephab

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "pom.xml"
      - ".github/workflows/main_touristguidephab.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin        # or 'microsoft' if you prefer
          java-version: '21'           # change to '17' if your pom targets 17
          cache: maven

      - name: Make mvnw executable (Linux)
        run: chmod +x mvnw

      # ✅ Skip tests so Surefire doesn't run
      - name: Build JAR (skip tests)
        run: ./mvnw -B -DskipTests clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_44C834E771524BACA6DAFC4156423165 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B37D42488B144458CF86343FF034A53 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C74A272CE3B43F786F4F7B150A1191D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'touristguidephab'
          slot-name: 'Production'
          package: '*.jar'
